apiVersion: apps/v1
kind: Deployment
metadata:
  name: apps-settings
spec:
  replicas: 1
  selector:
    matchLabels:
      app: settings
  template:
    metadata:
      labels:
        app: settings
    spec:
      containers:
        - name: app-settings
          image: app-settings
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: apps-settings-service
spec:
  selector:
    app: settings
  ports:
    - name: default
      protocol: TCP
      port: 8080
      targetPort: 80
