##########################################
# Add `127.0.0.1   foo.bar` to /etc/hosts
##########################################
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-passthrough: 'true'
spec:
  rules:
    - host: foo.bar
      http:
        paths:
          - path: /home
            pathType: Prefix
            backend:
              service:
                name: apps-home-service
                port:
                  number: 8080
          - path: /settings
            pathType: Prefix
            backend:
              service:
                name: apps-settings-service
                port:
                  number: 8080
          - path: /user
            pathType: Prefix
            backend:
              service:
                name: apps-user-service
                port:
                  number: 8080
